Map<String, Map<String, String>> allTranslations = {
  'en': {
    'Select Color': 'Select Color',
    'BlueGrey': 'BlueGrey',
    'Red': 'Red',
    'Green': 'Green',
    'Yellow': 'Yellow',
    'Orange': 'Orange',
    'Purple': 'Purple',
    'Pink': 'Pink',
    'Teal': 'Teal',
    'Cyan': 'Cyan',
    'Amber': 'Amber',
    'Deep Purple': 'Deep Purple',
    'Indigo': 'Indigo',
    'Change Background Color': 'Change Background Color',
    'Application Settings': 'Application Settings',
    'Clear Application Data': 'Clear Application Data',
    'Clear Data': 'Clear Data',
    'Are you sure you want to clear all user data ?': 'Are you sure you want to clear all user data ?',
    'Languages': 'Languages',
    'Settings': 'Settings',
    'OK': 'OK',
    'Cancel': 'Cancel',
  },
  'tr': {
    'Select Color': 'Renk Seçin',
    'BlueGrey': 'Mavi Gri',
    'Red': 'Kırmızı',
    'Green': 'Yeşil',
    'Yellow': 'Sarı',
    'Orange': 'Turuncu',
    'Purple': 'Mor',
    'Pink': 'Pembe',
    'Teal': 'Turkuaz',
    'Cyan': 'Cam Göbeği',
    'Amber': 'Amber',
    'Deep Purple': 'Koyu Mor',
    'Indigo': 'İndigo',
    'Change Background Color': 'Arka Plan Rengini Değiştir',
    'Application Settings': 'Uygulama Ayarları',
    'Clear Application Data': 'Uygulama Verilerini Temizle',
    'Clear Data': 'Verileri Temizle',
    'Are you sure you want to clear all user data ?': 'Tüm kullanıcı verilerini silmek istediğinizden emin misiniz?',
    'Languages': 'Dil Seçenekleri',
    'Settings': 'Ayarlar',
    'OK': 'Seç',
    'Cancel': 'Vazgeç',
  },
  'fr': {
    'Select Color': 'Sélectionnez une couleur',
    'BlueGrey': 'Gris Bleu',
    'Red': 'Rouge',
    'Green': 'Vert',
    'Yellow': 'Jaune',
    'Orange': 'Orange',
    'Purple': 'Violet',
    'Pink': 'Rose',
    'Teal': 'Turquoise',
    'Cyan': 'Cyan',
    'Amber': 'Ambre',
    'Deep Purple': 'Violet Foncé',
    'Indigo': 'Indigo',
    'Change Background Color': 'Changer la couleur',
    'Application Settings': 'Réglages',
    'Clear Application Data': 'Effacer données',
    'Clear Data': 'Effacer les données',
    'Are you sure you want to clear all user data ?':  'Êtes-vous sûr ?',
    'Languages': 'Langues',
    'Settings': 'Paramètres',
    'OK': 'OK',
    'Cancel': 'Annuler',
  },
};
